### PR TITLE
metrics-redis-graphite: fix skipkeys option not accepting any argument

### PR DESCRIPTION
**Pull request by boutetnico**
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

Fixes the `skipkeys` option that would not accept any argument (introduced in #31).

Output before this fix:

```
 $ /opt/sensu/embedded/bin/metrics-redis-graphite.rb -k role
Check failed to run: undefined method `split' for true:TrueClass, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-redis-1.2.1/bin/metrics-redis-graphite.rb:104:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

Output after the fix:

```
$ /opt/sensu/embedded/bin/metrics-redis-graphite.rb -k role | grep role
(empty result as expected)
```

### CODE REVIEW

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-redis/versions/1.2.2
